version: '3'

network: 
  laravel:

service:

nginx:
  image: nginx:stable-alpine
    container_name: nginx
  ports: 
    - "8080:80"
  volumes:
    - ./:/var/www
    - ./nginx/default.conf: /etc/nginx/conf.d/default.conf
  depends_on:
    - php
    - mysql
  network:
    - laravel
